apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/nats-io/nats-operator/master/deploy/10-deployment.yaml
  - nats-cluster.yml

namespace: default
